import './globals.css';
import { TrpcProvider } from "@/utils/trpc-provider";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-green-700 h-screen overflow-hidden">
      <TrpcProvider>{children}</TrpcProvider>
      </body>
    </html>
  )
}
